import type { Campaign, EnrolledCampaign, CompletedCampaign, Transaction, MonthlyEarning } from '@/types';

const baseMilestones = [
  { views: 500, minDaysLive: 7, incrementalPayout: 50, cumulativePayout: 50 },
  { views: 2500, minDaysLive: 15, incrementalPayout: 150, cumulativePayout: 200 },
  { views: 10000, minDaysLive: 30, incrementalPayout: 400, cumulativePayout: 600 },
  { views: 50000, minDaysLive: 30, incrementalPayout: 1000, cumulativePayout: 1600 },
  { views: 100000, minDaysLive: 45, incrementalPayout: 2500, cumulativePayout: 4100 },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'campaign-1',
    trackName: 'Bihu Beats',
    artistName: 'Zubeen Garg',
    albumArt: '',
    previewUrl: '',
    spotifyTrackId: 'track-assam-1',
    genre: 'Assamese',
    language: 'Assamese',
    pool: 50000,
    spotsTotal: 200,
    spotsFilled: 170,
    endsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: baseMilestones,
    status: 'open',
    isTrending: true,
    isNew: false,
    description: 'High-energy Bihu celebration campaign',
  },
  {
    id: 'campaign-2',
    trackName: 'Nongjang',
    artistName: 'Tonmoy Kumbang',
    albumArt: '',
    previewUrl: '',
    spotifyTrackId: 'track-manipur-1',
    genre: 'Manipuri',
    language: 'Manipuri',
    pool: 48000,
    spotsTotal: 200,
    spotsFilled: 156,
    endsAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: baseMilestones,
    status: 'open',
    isTrending: true,
    isNew: false,
    description: 'Manipuri folk-pop fusion campaign',
  },
  {
    id: 'campaign-3',
    trackName: 'Mizo Groove',
    artistName: 'Mami Varte',
    albumArt: '',
    previewUrl: '',
    spotifyTrackId: 'track-mizo-1',
    genre: 'Mizo',
    language: 'Mizo',
    pool: 45000,
    spotsTotal: 200,
    spotsFilled: 24,
    endsAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: baseMilestones,
    status: 'open',
    isTrending: false,
    isNew: true,
    description: 'Contemporary Mizo music campaign',
  },
  {
    id: 'campaign-4',
    trackName: 'Hills & Dreams',
    artistName: 'Tarali Sarma',
    albumArt: '',
    previewUrl: '',
    spotifyTrackId: 'track-assam-2',
    genre: 'Assamese Pop',
    language: 'Assamese',
    pool: 42000,
    spotsTotal: 200,
    spotsFilled: 16,
    endsAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: baseMilestones,
    status: 'open',
    isTrending: false,
    isNew: true,
    description: 'Poetic Assamese pop collaboration',
  },
  {
    id: 'campaign-5',
    trackName: 'Khorang',
    artistName: 'Papon',
    albumArt: '',
    previewUrl: '',
    spotifyTrackId: 'track-papon-1',
    genre: 'Hindi/Assamese',
    language: 'Hindi',
    pool: 60000,
    spotsTotal: 200,
    spotsFilled: 180,
    endsAt: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
    milestones: baseMilestones,
    status: 'open',
    isTrending: false,
    isNew: false,
    description: 'Bollywood-meets-Northeast fusion',
  },
  {
    id: 'campaign-6',
    trackName: 'Monsoon Love',
    artistName: 'Angaraag Mahanta',
    albumArt: '',
    previewUrl: '',
    spotifyTrackId: 'track-monsoon-1',
    genre: 'Hindi Pop',
    language: 'Hindi',
    pool: 55000,
    spotsTotal: 200,
    spotsFilled: 200,
    endsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: baseMilestones,
    status: 'full',
    isTrending: false,
    isNew: false,
    description: 'Romantic Hindi pop campaign',
  },
  {
    id: 'campaign-7',
    trackName: 'Luit Poriya',
    artistName: 'Anurag Saikia',
    albumArt: '',
    previewUrl: '',
    spotifyTrackId: 'track-assam-3',
    genre: 'Instrumental',
    language: 'Assamese',
    pool: 40000,
    spotsTotal: 200,
    spotsFilled: 90,
    endsAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: baseMilestones,
    status: 'open',
    isTrending: false,
    isNew: false,
    description: 'Classical-modern instrumental fusion',
  },
  {
    id: 'campaign-8',
    trackName: 'Thangal',
    artistName: 'Rewben Mashangva',
    albumArt: '',
    previewUrl: '',
    spotifyTrackId: 'track-naga-1',
    genre: 'Naga Folk',
    language: 'Tangkhul',
    pool: 38000,
    spotsTotal: 200,
    spotsFilled: 70,
    endsAt: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: baseMilestones,
    status: 'open',
    isTrending: false,
    isNew: false,
    description: 'Traditional Tangkhul Naga folk music',
  },
];

export const mockEnrolled: EnrolledCampaign[] = [
  {
    campaignId: 'campaign-1',
    submittedUrl: 'https://www.instagram.com/reel/abc123',
    platform: 'instagram',
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    verificationStatus: 'verified',
    currentViews: 2340,
    milestonesHit: [
      { views: 500, earnedAmount: 50 },
    ],
    earned: 50,
  },
  {
    campaignId: 'campaign-2',
    submittedUrl: 'https://www.instagram.com/reel/def456',
    platform: 'instagram',
    submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    verificationStatus: 'pending',
    currentViews: 0,
    milestonesHit: [],
    earned: 0,
  },
  {
    campaignId: 'campaign-3',
    submittedUrl: 'https://www.youtube.com/shorts/ghi789',
    platform: 'youtube',
    submittedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    verificationStatus: 'verified',
    currentViews: 8500,
    milestonesHit: [
      { views: 500, earnedAmount: 50 },
      { views: 2500, earnedAmount: 150 },
    ],
    earned: 200,
  },
];

// export const mockCompleted: CompletedCampaign[] = [
//   {
//     campaignId: 'campaign-old-1',
//     trackName: 'Raag & Roll',
//     artistName: 'Bhupen Hazarika Revival',
//     albumArt: '',
//     genre: 'Assamese Classic',
//     platform: 'instagram',
//     submittedUrl: 'https://www.instagram.com/reel/old123',
//     verificationStatus: 'verified',
//     finalViews: 15680,
//     totalEarned: 1200,
//     completedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
//     allMilestonesHit: false,
//   },
//   {
//     campaignId: 'campaign-old-2',
//     trackName: 'Valley Echo',
//     artistName: 'Aisha Pakhrin',
//     albumArt: '',
//     genre: 'Nepali Fusion',
//     platform: 'youtube',
//     submittedUrl: 'https://www.youtube.com/shorts/old456',
//     verificationStatus: 'verified',
//     finalViews: 5420,
//     totalEarned: 420,
//     completedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
//     allMilestonesHit: false,
//   },
// ];

export const mockTransactions: Transaction[] = [
  {
    id: 'txn-1',
    campaignId: 'campaign-1',
    trackName: 'Bihu Beats',
    milestone: 500,
    amount: 50,
    status: 'paid',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    upiRef: 'UPI401234567',
  },
  {
    id: 'txn-2',
    campaignId: 'campaign-2',
    trackName: 'Nongjang',
    milestone: 500,
    amount: 50,
    status: 'paid',
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    upiRef: 'UPI402345678',
  },
  {
    id: 'txn-3',
    campaignId: 'campaign-3',
    trackName: 'Mizo Groove',
    milestone: 2500,
    amount: 150,
    status: 'pending',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'txn-4',
    campaignId: 'campaign-old-1',
    trackName: 'Raag & Roll',
    milestone: 50000,
    amount: 1000,
    status: 'paid',
    date: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    upiRef: 'UPI403456789',
  },
  {
    id: 'txn-5',
    campaignId: 'campaign-5',
    trackName: 'Khorang',
    milestone: 500,
    amount: 50,
    status: 'rejected',
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'txn-6',
    campaignId: 'campaign-old-2',
    trackName: 'Valley Echo',
    milestone: 2500,
    amount: 150,
    status: 'paid',
    date: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    upiRef: 'UPI404567890',
  },
];

export const mockMonthlyData: MonthlyEarning[] = [
  { month: 'January', year: 2026, amount: 420, campaigns: 2 },
  { month: 'February', year: 2026, amount: 580, campaigns: 3 },
  { month: 'March', year: 2026, amount: 340, campaigns: 1 },
  { month: 'April', year: 2026, amount: 650, campaigns: 4 },
  { month: 'May', year: 2026, amount: 850, campaigns: 5 },
  { month: 'June', year: 2026, amount: 200, campaigns: 2 },
];
